### ISSUE TITLE
Can't run scripts in development install

### ISSUE THREAD

**Issue by ddobie** [askap-vast/vast-tools#305]
Not sure if I'm trying to do something completely idiotic, but I've just tried to run `find_sources.py` in the poetry dev install and hit the following error

```
Traceback (most recent call last):
  File "/usr/physics/python/anaconda3-201907/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/physics/python/anaconda3-201907/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/physics/python/anaconda3-201907/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (vasttools 2.0.0rc5 (/import/ada2/ddob1600/vast-tools), Requirement.parse('vasttools==2.0.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/suphys/ddob1600/.local/bin/find_sources.py", line 4, in <module>
    __import__('pkg_resources').require('vasttools==2.0.0')
  File "/usr/physics/python/anaconda3-201907/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/physics/python/anaconda3-201907/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/physics/python/anaconda3-201907/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/physics/python/anaconda3-201907/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/physics/python/anaconda3-201907/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/physics/python/anaconda3-201907/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vasttools==2.0.0' distribution was not found and is required by the application
```

This occurs whether I run `find_sources.py` or `poetry run find_sources.py`.

Previously I'd tested scripts using an editable pip install (i.e. installed with `pip install -e .`) but pip does not support editable installs for projects without a `setup.py`, which we no longer have.

**Comment by ddobie** [comment]
> Not sure if I'm trying to do something completely idiotic

This was the issue. 

Calling it without the .py works fine. I've got no idea why the error message is so cryptic (or where the rc.5 version came from - this was running on a completely fresh install), but I'm glad I've sorted it.

**Comment by ddobie** [comment]
Ah one slightly annoying thing - it seems like you have to run the script from within the vast-tools directory...

**Comment by ajstewart** [comment]
> Ah one slightly annoying thing - it seems like you have to run the script from within the vast-tools directory...

That shouldn't be the case either. It works as intended on my install:

```
 ~  pwd                                                               ✔  vast-tools-dev-poetry   
/Users/adam
 ~  which find_sources                                                ✔  vast-tools-dev-poetry   
/Users/adam/anaconda3/envs/vast-tools-dev-poetry/bin/find_sources
 ~  find_sources -h                                                   ✔  vast-tools-dev-poetry   
usage: find_sources [-h] [--coords COORDS] [--source-names SOURCE_NAMES] [--ncpu NCPU] [--epochs EPOCHS]
```

**Comment by ddobie** [comment]
Just did a completely fresh install and it's working now. How weird.
